apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DavGal42/argocd-app-of-apps.git
    targetRevision: HEAD
    path: apps/vote
  destination:
    server: https://kubernetes.default.svc
    namespace: vote
  syncPolicy:
    automated: {}
